#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/launcher/src/main/resources/org/gradle/launcher/bin/gradle
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${app_path##*/}
# Discard cd standard output in case $CDPATH is set https://github.com/gradle/gradle/issues/25036
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order to eventually pass to java.
# We cannot use "$@" because it could be made empty by splitting arguments over multiple lines.

# We might have to delegate argument parsing to a Java executable to be able to:
#   * detect '-x' and unpack -Dkey=value arguments that come before the main class, or
#   * handle cases where the main class is 'gradle.wrapper.GradleWrapperMain' and the 
#     application 'properties' task should be run, etc.

# Decode and use JVM options, environment variables, and command-line arguments.
# JVM options are those that start with '-D', '-X', or '-XX:'. 
# Environment variables are GRADLE_OPTS, JAVA_OPTS, and DEFAULT_JVM_OPTS.
# Command-line arguments are the rest.

# Set DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS variables if they are not already set.
# These variables control the JVM execution.
DEFAULT_JVM_OPTS=${DEFAULT_JVM_OPTS:-"-Xmx64m" "-Xms64m"}
JAVA_OPTS=${JAVA_OPTS:-}
GRADLE_OPTS=${GRADLE_OPTS:-}

# We use a subshell to isolate the argument collection process from the current shell.
# The subshell's output is captured and used to set the final arguments.
# This is done in a subshell to avoid polluting the current environment with temporary variables.
(
    # Print the help message if the first argument is '-h' or '--help'.
    # This is not the only help check; the wrapper script also checks for help in the Java code.
    if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
        cat <<EOF
Usage: gradlew [option...] [task...]

Options:
  -h, --help                 Show this help message and exit.
  -D<name>=<value>           Set a system property.
  -P<name>=<value>           Set a project property.
  --no-daemon                Do not use the Gradle daemon.
  --daemon                   Use the Gradle daemon (default).
  --stop                     Stop the Gradle daemon.
  --status                   Show status of running daemons.
  --no-build-cache           Disable the build cache.
  --build-cache              Enable the build cache.
  --configuration-cache      Enable the configuration cache.
  --no-configuration-cache   Disable the configuration cache.
  --configuration-cache-problems={fail,warn}
                             Configure action on configuration cache problems.
  --refresh-keys             Refresh keys used for signing build scripts.
  --export-keys              Export public keys used for dependency verification.
  --update-locks <group:module>...
                             Update dependency lock for given modules.
  --write-locks              Write dependency lock state.
  --build-file, -b <file>    Specify the build file.
  --settings-file, -c <file> Specify the settings file.
  --gradle-user-home <dir>   Specify the Gradle user home directory.
  --project-cache-dir <dir>  Specify the project cache directory.
  --project-dir <dir>        Specify the start directory for Gradle.
  --include-build <dir>      Include the specified build in the composite.
  --offline                  Work without accessing network resources.
  --refresh-dependencies     Refresh the state of dependencies.
  --parallel                 Build projects in parallel.
  --no-parallel              Disable parallel project execution.
  --max-workers <n>          Set the maximum number of workers.
  --configure-on-demand      Only configure necessary projects.
  --no-configure-on-demand   Disable configure on demand.
  --continuous, -t           Continuous build (listen for file changes).
  --no-continuous            Disable continuous build.
  --rerun-tasks              Ignore previously cached task results.
  --profile                  Generate profile report.
  --scan                     Create a build scan.
  --no-scan                  Disable build scan creation.
  --info                     Set log level to info.
  --debug                    Set log level to debug.
  --quiet, -q                Set log level to quiet (errors only).
  --warn                     Set log level to warn.
  --stacktrace               Print out the stacktrace for all exceptions.
  --full-stacktrace          Print out the full (very verbose) stacktrace.
  --no-stacktrace            Do not print stacktraces.
  --build-cache-debug        Show build cache debug information.
  --no-build-cache-debug     Disable build cache debug output.
  --help                     Show this help message and exit.

Tasks:
  tasks                      Displays the tasks runnable from root project.
  build                      Assembles and tests this project.
  assemble                   Assembles the outputs of this project.
  check                      Runs all checks.
  clean                      Deletes the build directory.
  test                       Runs the unit tests.
  javadoc                    Generates Javadoc API documentation for the main source code.
  wrapper                    Generates Gradle wrapper files.

Project-specific tasks can be found by running './gradlew tasks'.

Example:
  ./gradlew build
EOF
        exit 0
    fi

    # Collect all arguments, handling multi-line arguments and globs.
    # We want to collect them in a way that preserves any quoting and escaping.
    # This loop will append each argument to the array '$@' after processing.
    while [ $# -gt 0 ]; do
        # Save the current argument for later processing.
        arg="$1"
        shift

        # If the argument is a file, expand it (handles globs and directories).
        # This is needed for passing file names that contain spaces, for example.
        # We use 'test -f' to check if it's a file.
        # Note: This is not 100% reliable because it doesn't handle symlinks or other special files perfectly.
        if [ -f "$arg" ]; then
            # If it's a file, add it as is.
            set -- "$@" "$arg"
        else
            # For non-file arguments, we need to handle quoting and escaping.
            # This is tricky in a POSIX shell, but we can use 'printf' to do it.
            # We'll just add the argument as is; Java will handle escaping.
            set -- "$@" "$arg"
        fi
    done

    # Pass the collected arguments to the Java command.
    exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
) || die "Failed to execute Gradle"
